### ISSUE TITLE
Request: add this to mbin software

### ISSUE THREAD

**Issue by TheVillageGuy** [teampanfu/oauth2-discord#1]
I'd like to ask if somebody could add this functionality to [mbin](https://github.com/MbinOrg/mbin) it already has Facebook & gmail, discord would be very helpful. I don't know where else to ask, the mbin devs are busy developing and I don't have any oauth experience myself

Thank you

**Comment by teampanfu** [comment]
We only provide the package, the implementation is not our responsibility. You should create an issue there.
